<Project>

  <PropertyGroup Label="Lang">    
    <ImplicitUsings>disable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <LangVersion>latest</LangVersion>
    <AllowUnsafeBlocks>False</AllowUnsafeBlocks>
    <EnforceCodeStyleInBuild>True</EnforceCodeStyleInBuild>
    <AnalysisLevel>latest-all</AnalysisLevel>
  </PropertyGroup>

  <PropertyGroup Label="Id">
    <Authors>software9119.technology</Authors>
    <Company>software9119.technology</Company>
    <Copyright>MIT</Copyright>
    <PackageLicenseExpression>MIT</PackageLicenseExpression>    
    <PackageRequireLicenseAcceptance>false</PackageRequireLicenseAcceptance>
  </PropertyGroup>

  <PropertyGroup Label="Determinism">
    <Deterministic>false</Deterministic>
    <ContinuousIntegrationBuild>false</ContinuousIntegrationBuild>
  </PropertyGroup>

  <PropertyGroup Label="Debug">
    <RepositoryUrl>https://github.com/deep-outcome/Software9119.ProxyNsAnalyzer</RepositoryUrl>
    <PublishRepositoryUrl>true</PublishRepositoryUrl>
    <EmbedUntrackedSources>false</EmbedUntrackedSources>
    <DebugSymbols>true</DebugSymbols>
    <DebugType>portable</DebugType>
    <IncludeSymbols>false</IncludeSymbols>
    <SymbolPackageFormat>snupkg</SymbolPackageFormat>
    <AllowedOutputExtensionsInPackageBuildOutputFolder>$(AllowedOutputExtensionsInPackageBuildOutputFolder);.pdb</AllowedOutputExtensionsInPackageBuildOutputFolder>
  </PropertyGroup>

</Project>